
package com.mahendra;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AccountService", targetNamespace = "mahendra.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AccountService {


    /**
     * 
     * @return
     *     returns java.util.List<com.mahendra.Account>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllAccounts", targetNamespace = "mahendra.com", className = "com.mahendra.GetAllAccounts")
    @ResponseWrapper(localName = "getAllAccountsResponse", targetNamespace = "mahendra.com", className = "com.mahendra.GetAllAccountsResponse")
    @Action(input = "mahendra.com/AccountService/getAllAccountsRequest", output = "mahendra.com/AccountService/getAllAccountsResponse")
    public List<Account> getAllAccounts();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.mahendra.Account
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "find", targetNamespace = "mahendra.com", className = "com.mahendra.Find")
    @ResponseWrapper(localName = "findResponse", targetNamespace = "mahendra.com", className = "com.mahendra.FindResponse")
    @Action(input = "mahendra.com/AccountService/findRequest", output = "mahendra.com/AccountService/findResponse")
    public Account find(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

}
